apiVersion: apps/v1
kind: Deployment
metadata:
  name: r-operator
  namespace: r-operator-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - name: manager
        image: r-operator:latest
        command:
        - /manager
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
      serviceAccountName: r-operator-controller-manager
      terminationGracePeriodSeconds: 10